apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat 
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true" 