apiVersion: batch/v1
kind: Job
metadata:
  name: curl-nginx
  labels:
    app: curl
spec:
  template:
    spec:
      containers:
      - name: curl
        image: curlimages/curl:7.73.0
        command: ["/bin/sh", "-ec", "curl -iv http://nginx.opentlc-mgr-nginx:8080/"]
      restartPolicy: Never