apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: ubuntu:20.04
        command: ["/bin/bash", "-ec", "while :; do echo 'Hello World'; sleep 5 ; done"]
        resources:
          requests:
            cpu: 50m
            memory: 10Mi
          limits:
            cpu: 500m
            memory: 100Mi