apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  containers:
  - name: hello-world
    image: ubuntu:20.04
    command: ["/bin/bash", "-ec", "while :; do echo 'Hello World'; sleep 5 ; done"]