apiVersion: gpte.opentlc.com/v1
kind: Gitea
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: repository
spec:
  giteaImageTag: latest
  giteaSsl: false
  giteaVolumeSize: 4Gi
  postgresqlVolumeSize: 4Gi