apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: init-config/namespaces/chart
    repoURL: https://github.com/ccdgrundhoefer/rhpds-init.git
    helm:
      valueFiles:
        - ../values/workshop.yaml
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true