{{- range $.Values.users }}
{{- $user := . -}}
{{- range $.Values.projects -}}
{{- $project := printf "%v-%v" $user . -}}
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  namespace: {{ $project }}
spec:
  resourceExclusions: |
    - apiGroups:
      - "*"
      kinds:
      - "PipelineRun"
      - "TaskRun"
      clusters:
      - "*"
  controller:
    processors:
      operation: 20
      status: 20
    resources: 
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 2
        memory: 3Gi
  dex:
    openShiftOAuth: true
  server:
    route: 
      enabled: true
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, system:authenticated, role:admin
      g, pipeline, role:admin
    scopes: '[groups]'
  version: v2.3.4
{{ end }}
{{ end }}