apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    prometheusK8s: 
      retention: 7d
      volumeClaimTemplate:
       spec:
         storageClassName: gp2-csi
         resources:
           requests:
             storage: 10Gi