apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus: 
      volumeClaimTemplate:
       spec:
         storageClassName: gp2-csi
         resources:
           requests:
             storage: 10Gi
      retention: 7d
      resources:
        requests:
          cpu: 200m 
          memory: 2Gi